// @generated by ccc from concept card. Do not edit.
export type Suit = '♠' | '♥' | '♦' | '♣';
export type Rank = '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | 'J' | 'Q' | 'K' | 'A';
export interface Card {
  readonly rank: Rank;
  readonly suit: Suit;
}
export const SUITS: readonly Suit[];
export const RANKS: readonly Rank[];
export function card(rank: Rank, suit: Suit): Card;
export function sameCard(a: Card, b: Card): boolean;
export function beats(a: Card, b: Card): boolean;
