// @generated by ccc from concept leaderboard-store. Do not edit.
import { Standing } from './leaderboard.js';
import { UserId } from './user.js';
import type { Database } from '@ccc/runtime';
export class LeaderboardStore {
  constructor(db: Database);
  recordWin(user: UserId): Promise<void>;
  top(limit: number): Promise<Standing[]>;
}
