// @generated by ccc from concept leaderboard. Do not edit.
import { UserId, userId } from './user.js';
export interface Standing {
  readonly userId: UserId;
  readonly wins: number;
}
export class Leaderboard {
  constructor(standings?: readonly Standing[]);
  recordWin(user: UserId): void;
  top(limit: number): readonly Standing[];
}
