// @generated by ccc from concept leaderboard-api. Do not edit.
import { LeaderboardStore } from './leaderboard-store.js';
import type { Database } from '@ccc/runtime';
export interface LeaderboardApiDeps {
  readonly db: Database;
  readonly leaderboardStore: LeaderboardStore;
}
export function createHandler(deps: LeaderboardApiDeps): (request: Request) => Promise<Response>;
