// @generated by ccc from sync record-winner. Do not edit.
import { Game } from './game.js';
import { LeaderboardStore } from './leaderboard-store.js';

export interface SyncEvent {
  readonly target: Game;
  readonly args: Parameters<Game['play']>;
  readonly result: Awaited<ReturnType<Game['play']>>;
}
export interface SyncTargets {
  readonly leaderboardStore: LeaderboardStore;
}
export function handle(event: SyncEvent, targets: SyncTargets): Promise<void>;
