// @generated by ccc from concept game.deal-on-full-table. Do not edit.
import * as impl from '../../gen/game/deal-on-full-table.js';
import type * as iface from '../../gen/game/deal-on-full-table.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
export const type_SyncEvent: Equal<impl.SyncEvent, iface.SyncEvent> extends true ? true : 'SyncEvent differs from the interface' = true;
export const type_SyncTargets: Equal<impl.SyncTargets, iface.SyncTargets> extends true ? true : 'SyncTargets differs from the interface' = true;
