// @generated by ccc from concept game.players. Do not edit.
import * as impl from '../../gen/game/players.js';
import type * as iface from '../../gen/game/players.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
