// @generated by ccc from concept game.deck. Do not edit.
import { Card } from '../card.js';
export class EmptyDeck extends Error {}
export class Deck {
  constructor(cards: readonly Card[]);
  static standard(): Deck;
  shuffled(seed: number): Deck;
  draw(): Card;
  size(): number;
  cards(): readonly Card[];
}
