// @generated by ccc from concept game.players. Do not edit.
import { Player } from './player.js';
import { UserId } from '../user.js';
import type { Conflict } from '@ccc/runtime';
export class TableFull extends Conflict {}
export class AlreadySeated extends Conflict {}
export class Players {
  constructor(seats: number, seated?: readonly Player[]);
  join(user: UserId): Player;
  seats(): number;
  seatsLeft(): number;
  all(): readonly Player[];
  byUser(user: UserId): Player | undefined;
}
