// @generated by ccc from concept game.player. Do not edit.
import { Hand } from './player/hand.js';
import { UserId } from '../user.js';
export class Player {
  constructor(user: UserId, hand?: Hand, points?: number);
  readonly user: UserId;
  readonly hand: Hand;
  points(): number;
  scorePoint(): void;
}
