// @generated by ccc from concept auth. Do not edit.
import * as impl from '../gen/auth.js';
import type * as iface from '../gen/auth.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
export const type_Session: Equal<impl.Session, iface.Session> extends true ? true : 'Session differs from the interface' = true;
export const type_Identity: Equal<impl.Identity, iface.Identity> extends true ? true : 'Identity differs from the interface' = true;
