// @generated by ccc from concept auth-api. Do not edit.
import * as impl from '../gen/auth-api.js';
import type * as iface from '../gen/auth-api.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
export const type_AuthApiDeps: Equal<impl.AuthApiDeps, iface.AuthApiDeps> extends true ? true : 'AuthApiDeps differs from the interface' = true;
