// @generated by ccc from concept card. Do not edit.
import * as impl from '../gen/card.js';
import type * as iface from '../gen/card.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
export const type_Suit: Equal<impl.Suit, iface.Suit> extends true ? true : 'Suit differs from the interface' = true;
export const type_Rank: Equal<impl.Rank, iface.Rank> extends true ? true : 'Rank differs from the interface' = true;
export const type_Card: Equal<impl.Card, iface.Card> extends true ? true : 'Card differs from the interface' = true;
