// @generated by ccc from concept game-api. Do not edit.
import * as impl from '../gen/game-api.js';
import type * as iface from '../gen/game-api.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
export const type_GameApiDeps: Equal<impl.GameApiDeps, iface.GameApiDeps> extends true ? true : 'GameApiDeps differs from the interface' = true;
