// @generated by ccc from concept game. Do not edit.
import * as impl from '../gen/game.js';
import type * as iface from '../gen/game.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
export const type_GameStatus: Equal<impl.GameStatus, iface.GameStatus> extends true ? true : 'GameStatus differs from the interface' = true;
export const type_PlayResult: Equal<impl.PlayResult, iface.PlayResult> extends true ? true : 'PlayResult differs from the interface' = true;
export const type_PlayerView: Equal<impl.PlayerView, iface.PlayerView> extends true ? true : 'PlayerView differs from the interface' = true;
export const type_TablePlay: Equal<impl.TablePlay, iface.TablePlay> extends true ? true : 'TablePlay differs from the interface' = true;
export const type_GameView: Equal<impl.GameView, iface.GameView> extends true ? true : 'GameView differs from the interface' = true;
export const type_SeatState: Equal<impl.SeatState, iface.SeatState> extends true ? true : 'SeatState differs from the interface' = true;
export const type_PlayState: Equal<impl.PlayState, iface.PlayState> extends true ? true : 'PlayState differs from the interface' = true;
export const type_GameState: Equal<impl.GameState, iface.GameState> extends true ? true : 'GameState differs from the interface' = true;
