// @generated by ccc from concept game-store. Do not edit.
import * as impl from '../gen/game-store.js';
import type * as iface from '../gen/game-store.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
