// @generated by ccc from concept leaderboard. Do not edit.
import * as impl from '../gen/leaderboard.js';
import type * as iface from '../gen/leaderboard.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
export const type_Standing: Equal<impl.Standing, iface.Standing> extends true ? true : 'Standing differs from the interface' = true;
