// @generated by ccc from concept user. Do not edit.
import * as impl from '../gen/user.js';
import type * as iface from '../gen/user.contract.js';

export const conforms: typeof iface = impl;
type Extra = Exclude<keyof typeof impl, keyof typeof iface>;
export const noExtraExports: [Extra] extends [never] ? true : Extra = true;
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2) ? true : false;
export const type_UserId: Equal<impl.UserId, iface.UserId> extends true ? true : 'UserId differs from the interface' = true;
