import type { FakeResponder } from './fake-generator.js';
import { linkPackages, writeProject } from './helpers.js';
import { artifactOf, conceptOf } from './pipeline-fixture.js';

// A tally service: an aggregate, two stores, a sync whose target is a store
// singleton, and an HTTP endpoint that binds the aggregate in scope.
export const ADAPTER_FILES: Readonly<Record<string, string>> = {
  'package.json': '{ "type": "module" }\n',
  'concepts/tally.md': [
    '---',
    'kind: aggregate',
    'interface: |',
    '  export class InvalidAmount extends Error {}',
    '  export class Tally {',
    '    constructor(id: string);',
    '    static restore(id: string, count: number): Tally;',
    '    readonly id: string;',
    '    count(): number;',
    '    add(amount: number): void;',
    '  }',
    '---',
    '## Intent',
    'A running total.',
    '',
    '## Rules',
    '- Amounts must be positive integers.',
    '',
    '## Examples',
    '- new Tally("t").count() → 0',
    '- given a tally, add(2) then add(3) → count() is 5',
    '- add(0) → throws InvalidAmount',
    '',
  ].join('\n'),
  'concepts/tally-store.md': [
    '---',
    'kind: store',
    'persists: tally',
    'interface: |',
    "  import type { Database } from '@ccc/runtime';",
    '  export class TallyStore {',
    '    constructor(db: Database);',
    '    load(id: string): Promise<Tally | null>;',
    '    save(tally: Tally): Promise<void>;',
    '  }',
    '---',
    '## Intent',
    'Saves and loads tallies.',
    '',
    '## Schema',
    '```sql',
    'create table tallies (',
    '  id text primary key,',
    '  count integer not null',
    ');',
    '```',
    '',
    '## Examples',
    '- save(a tally with count 4) then load(its id) → a tally with count 4',
    '- load("missing") → null',
    '',
  ].join('\n'),
  'concepts/tally-audit.md': [
    '---',
    'kind: store',
    'persists: tally',
    'interface: |',
    "  import type { Database } from '@ccc/runtime';",
    '  export class TallyAudit {',
    '    constructor(db: Database);',
    '    record(tallyId: string, amount: number): Promise<void>;',
    '    entries(tallyId: string): Promise<number[]>;',
    '  }',
    '---',
    '## Intent',
    'An append-only log of amounts added to each tally.',
    '',
    '## Schema',
    '```sql',
    'create table tally_audit (',
    '  seq serial primary key,',
    '  tally_id text not null,',
    '  amount integer not null',
    ');',
    '```',
    '',
    '## Examples',
    '- record("t", 2) then record("t", 3) → entries("t") is [2, 3]',
    '- entries("none") → []',
    '',
  ].join('\n'),
  'concepts/audit-adds.md': [
    '---',
    'kind: sync',
    'when: tally#add',
    'then: [tally-audit#record]',
    '---',
    '## Intent',
    'Record every amount added to a tally.',
    '',
    '## Examples',
    '- given tally "t" and an audit log, add(2) → the audit log records 2 for "t"',
    '',
  ].join('\n'),
  'concepts/tally-api.md': [
    '---',
    'kind: endpoint',
    'uses: [tally, tally-store, tally-audit]',
    'interface: |',
    "  import type { Database } from '@ccc/runtime';",
    '  export interface TallyApiDeps {',
    '    readonly db: Database;',
    '    readonly tallyStore: TallyStore;',
    '    readonly tallyAudit: TallyAudit;',
    '  }',
    '  export function createHandler(deps: TallyApiDeps): (request: Request) => Promise<Response>;',
    '---',
    '## Intent',
    'HTTP access to tallies.',
    '',
    '## Examples',
    '- POST /tallies/t/add {"amount": 2}, then {"amount": 3} → 200 {"count": 5}',
    '- after adding 2 and 3 to tally t, GET /tallies/t/audit → 200 [2, 3]',
    '- POST /tallies/t/add {"amount": 0} → 400',
    '- GET /elsewhere → 404',
    '',
  ].join('\n'),
  // Reads every request body and handles nothing: the live requests only
  // work if each endpoint gets its own copy of the request.
  'concepts/peek-api.md': [
    '---',
    'kind: endpoint',
    'interface: |',
    '  export function createHandler(deps: object): (request: Request) => Promise<Response>;',
    '---',
    '## Intent',
    'Reads every request body and handles nothing.',
    '',
    '## Examples',
    '- any request → 404 (unmatched)',
    '',
  ].join('\n'),
};

export const ADAPTER_TESTS: Readonly<Record<string, string>> = {
  tally: [
    "import { InvalidAmount, Tally } from './tally.js';",
    '',
    "describe('Tally', () => {",
    "  it('[ex 1] starts at zero', () => {",
    "    expect(new Tally('t').count()).toBe(0);",
    '  });',
    "  it('[ex 2] adds amounts', () => {",
    "    const tally = new Tally('t');",
    '    tally.add(2);',
    '    tally.add(3);',
    '    expect(tally.count()).toBe(5);',
    '  });',
    "  it('[ex 3] rejects a zero amount', () => {",
    "    expect(() => new Tally('t').add(0)).toThrow(InvalidAmount);",
    '  });',
    '});',
    '',
  ].join('\n'),
  'tally-store': [
    "import { pgliteDatabase } from '@ccc/runtime/pglite';",
    "import { schemaSql } from './schema.js';",
    "import { Tally } from './tally.js';",
    "import { TallyStore } from './tally-store.js';",
    '',
    'async function store(): Promise<TallyStore> {',
    '  const db = pgliteDatabase();',
    '  await db.exec(schemaSql);',
    '  return new TallyStore(db);',
    '}',
    '',
    "describe('TallyStore', () => {",
    "  it('[ex 1] round-trips a tally', async () => {",
    '    const tallies = await store();',
    "    const tally = new Tally('t1');",
    '    tally.add(4);',
    '    await tallies.save(tally);',
    "    expect((await tallies.load('t1'))?.count()).toBe(4);",
    '  });',
    "  it('[ex 2] returns null for a missing tally', async () => {",
    "    expect(await (await store()).load('missing')).toBeNull();",
    '  });',
    '});',
    '',
  ].join('\n'),
  'tally-audit': [
    "import { pgliteDatabase } from '@ccc/runtime/pglite';",
    "import { schemaSql } from './schema.js';",
    "import { TallyAudit } from './tally-audit.js';",
    '',
    'async function audit(): Promise<TallyAudit> {',
    '  const db = pgliteDatabase();',
    '  await db.exec(schemaSql);',
    '  return new TallyAudit(db);',
    '}',
    '',
    "describe('TallyAudit', () => {",
    "  it('[ex 1] lists recorded amounts in order', async () => {",
    '    const log = await audit();',
    "    await log.record('t', 2);",
    "    await log.record('t', 3);",
    "    expect(await log.entries('t')).toEqual([2, 3]);",
    '  });',
    "  it('[ex 2] is empty for an unknown tally', async () => {",
    "    expect(await (await audit()).entries('none')).toEqual([]);",
    '  });',
    '});',
    '',
  ].join('\n'),
  'audit-adds': [
    "import { pgliteDatabase } from '@ccc/runtime/pglite';",
    "import { handle } from './audit-adds.js';",
    "import { schemaSql } from './schema.js';",
    "import { Tally } from './tally.js';",
    "import { TallyAudit } from './tally-audit.js';",
    '',
    "describe('audit-adds', () => {",
    "  it('[ex 1] records the amount added', async () => {",
    '    const db = pgliteDatabase();',
    '    await db.exec(schemaSql);',
    '    const audit = new TallyAudit(db);',
    "    await handle({ target: new Tally('t'), args: [2], result: undefined }, { tallyAudit: audit });",
    "    expect(await audit.entries('t')).toEqual([2]);",
    '  });',
    '});',
    '',
  ].join('\n'),
  'tally-api': [
    "import { pgliteDatabase } from '@ccc/runtime/pglite';",
    "import { schemaSql } from './schema.js';",
    "import { createApp } from './server.js';",
    '',
    'async function app() {',
    '  const db = pgliteDatabase();',
    '  await db.exec(schemaSql);',
    "  return createApp(db, { endpoints: ['tally-api'] });",
    '}',
    '',
    'function add(amount: number): Request {',
    "  return new Request('http://test/tallies/t/add', {",
    "    method: 'POST',",
    "    headers: { 'content-type': 'application/json' },",
    '    body: JSON.stringify({ amount }),',
    '  });',
    '}',
    '',
    "describe('tally-api', () => {",
    "  it('[ex 1] adds to a tally', async () => {",
    '    const handler = await app();',
    '    await handler(add(2));',
    '    const response = await handler(add(3));',
    '    expect(response.status).toBe(200);',
    '    expect(await response.json()).toEqual({ count: 5 });',
    '  });',
    "  it('[ex 2] lists audited amounts', async () => {",
    '    const handler = await app();',
    '    await handler(add(2));',
    '    await handler(add(3));',
    "    const response = await handler(new Request('http://test/tallies/t/audit'));",
    '    expect(response.status).toBe(200);',
    '    expect(await response.json()).toEqual([2, 3]);',
    '  });',
    "  it('[ex 3] rejects a zero amount', async () => {",
    '    expect((await (await app())(add(0))).status).toBe(400);',
    '  });',
    "  it('[ex 4] does not handle other routes', async () => {",
    "    expect((await (await app())(new Request('http://test/elsewhere'))).status).toBe(404);",
    '  });',
    '});',
    '',
  ].join('\n'),
  'peek-api': [
    "import { pgliteDatabase } from '@ccc/runtime/pglite';",
    "import { createApp } from './server.js';",
    '',
    "it('[ex 1] handles nothing', async () => {",
    "  const app = await createApp(pgliteDatabase(), { endpoints: ['peek-api'] });",
    "  expect((await app(new Request('http://test/x', { method: 'POST', body: 'hello' }))).status).toBe(404);",
    '});',
    '',
  ].join('\n'),
};

export const ADAPTER_IMPL: Readonly<Record<string, string>> = {
  tally: [
    'export class InvalidAmount extends Error {}',
    '',
    'export class Tally {',
    '  readonly id: string;',
    '  #count = 0;',
    '',
    '  constructor(id: string) {',
    '    this.id = id;',
    '  }',
    '',
    '  static restore(id: string, count: number): Tally {',
    '    const tally = new Tally(id);',
    '    tally.#count = count;',
    '    return tally;',
    '  }',
    '',
    '  count(): number {',
    '    return this.#count;',
    '  }',
    '',
    '  add(amount: number): void {',
    '    if (!Number.isInteger(amount) || amount <= 0) {',
    '      throw new InvalidAmount(`amount must be a positive integer, got ${amount}`);',
    '    }',
    '    this.#count += amount;',
    '  }',
    '}',
    '',
  ].join('\n'),
  'tally-store': [
    "import type { Database } from '@ccc/runtime';",
    "import { Tally } from './tally.js';",
    '',
    'type TallyRow = { readonly id: string; readonly count: number };',
    '',
    'export class TallyStore {',
    '  readonly #db: Database;',
    '',
    '  constructor(db: Database) {',
    '    this.#db = db;',
    '  }',
    '',
    '  async load(id: string): Promise<Tally | null> {',
    "    const { rows } = await this.#db.query<TallyRow>('select id, count from tallies where id = $1', [id]);",
    '    const row = rows[0];',
    '    return row === undefined ? null : Tally.restore(row.id, row.count);',
    '  }',
    '',
    '  async save(tally: Tally): Promise<void> {',
    '    await this.#db.query(',
    "      'insert into tallies (id, count) values ($1, $2) on conflict (id) do update set count = excluded.count',",
    '      [tally.id, tally.count()],',
    '    );',
    '  }',
    '}',
    '',
  ].join('\n'),
  'tally-audit': [
    "import type { Database } from '@ccc/runtime';",
    '',
    'type EntryRow = { readonly amount: number };',
    '',
    'export class TallyAudit {',
    '  readonly #db: Database;',
    '',
    '  constructor(db: Database) {',
    '    this.#db = db;',
    '  }',
    '',
    '  async record(tallyId: string, amount: number): Promise<void> {',
    "    await this.#db.query('insert into tally_audit (tally_id, amount) values ($1, $2)', [tallyId, amount]);",
    '  }',
    '',
    '  async entries(tallyId: string): Promise<number[]> {',
    "    const { rows } = await this.#db.query<EntryRow>('select amount from tally_audit where tally_id = $1 order by seq', [tallyId]);",
    '    return rows.map((row) => row.amount);',
    '  }',
    '}',
    '',
  ].join('\n'),
  'audit-adds': [
    "import type { Tally } from './tally.js';",
    "import type { TallyAudit } from './tally-audit.js';",
    '',
    'export interface SyncEvent {',
    '  readonly target: Tally;',
    "  readonly args: Parameters<Tally['add']>;",
    "  readonly result: Awaited<ReturnType<Tally['add']>>;",
    '}',
    '',
    'export interface SyncTargets {',
    '  readonly tallyAudit: TallyAudit;',
    '}',
    '',
    'export async function handle(event: SyncEvent, targets: SyncTargets): Promise<void> {',
    '  await targets.tallyAudit.record(event.target.id, event.args[0]);',
    '}',
    '',
  ].join('\n'),
  'tally-api': [
    "import { Invalid, errorResponse, unmatched, withScope, type Database } from '@ccc/runtime';",
    "import { Hono } from 'hono';",
    "import { z } from 'zod';",
    "import { InvalidAmount, Tally } from './tally.js';",
    "import type { TallyAudit } from './tally-audit.js';",
    "import type { TallyStore } from './tally-store.js';",
    '',
    'export interface TallyApiDeps {',
    '  readonly db: Database;',
    '  readonly tallyStore: TallyStore;',
    '  readonly tallyAudit: TallyAudit;',
    '}',
    '',
    'const addBody = z.object({ amount: z.number() });',
    '',
    'export function createHandler(deps: TallyApiDeps): (request: Request) => Promise<Response> {',
    '  const app = new Hono();',
    "  app.post('/tallies/:id/add', async (c) => {",
    '    const parsed = addBody.safeParse(await c.req.json());',
    '    if (!parsed.success) {',
    "      return errorResponse(new Invalid('amount must be a number'));",
    '    }',
    "    const id = c.req.param('id');",
    '    const tally = (await deps.tallyStore.load(id)) ?? new Tally(id);',
    '    try {',
    '      await withScope({ tally }, async () => {',
    '        tally.add(parsed.data.amount);',
    '      });',
    '    } catch (err) {',
    '      if (err instanceof InvalidAmount) {',
    '        return errorResponse(new Invalid(err.message));',
    '      }',
    '      throw err;',
    '    }',
    '    await deps.tallyStore.save(tally);',
    '    return c.json({ count: tally.count() });',
    '  });',
    "  app.get('/tallies/:id/audit', async (c) => c.json(await deps.tallyAudit.entries(c.req.param('id'))));",
    '  app.notFound(() => unmatched());',
    '  return async (request) => app.fetch(request);',
    '}',
    '',
  ].join('\n'),
  'peek-api': [
    "import { unmatched } from '@ccc/runtime';",
    '',
    'export function createHandler(_deps: object): (request: Request) => Promise<Response> {',
    '  return async (request) => {',
    '    await request.text();',
    '    return unmatched();',
    '  };',
    '}',
    '',
  ].join('\n'),
};

export function adapterResponder(): FakeResponder {
  return (request) => {
    const id = conceptOf(request);
    return (artifactOf(request) === 'tests' ? ADAPTER_TESTS : ADAPTER_IMPL)[id] ?? null;
  };
}

export async function createAdapterProject(): Promise<string> {
  const root = await writeProject({ ...ADAPTER_FILES });
  await linkPackages(root, ['@ccc/runtime', 'hono', 'zod']);
  return root;
}
