import { cp, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import { dependencyClosure, runBuild, topologicalLevels } from '../src/build.js';
import { fileHash, readFileOrNull, writeFileAtomic } from '../src/fsutil.js';
import { modulePath, testPath } from '../src/layout.js';
import { loadProject } from '../src/load.js';
import { readManifest } from '../src/manifest.js';
import { FakeGenerator } from './fake-generator.js';
import { CANNED_IMPL, PIPELINE_FILES, createPipelineProject, pipelineResponder, type Overrides } from './pipeline-fixture.js';

async function copyProject(root: string): Promise<string> {
  const copy = await mkdtemp(path.join(tmpdir(), 'ccc-build-'));
  await cp(root, copy, { recursive: true });
  return copy;
}

async function build(root: string, overrides: Overrides = {}, extra: { only?: string; dryRun?: boolean; testsOnly?: boolean } = {}) {
  const fake = new FakeGenerator(pipelineResponder(overrides));
  const result = await runBuild({ root, generator: fake, ...extra });
  return { fake, result };
}

describe('topologicalLevels / dependencyClosure', () => {
  it('orders concepts by dependency depth', async () => {
    const root = await createPipelineProject();
    const { project } = await loadProject(root);
    expect(topologicalLevels(project)).toEqual([['card', 'counter'], ['hand'], ['count-adds']]);
    expect([...dependencyClosure(project, 'hand')].sort()).toEqual(['card', 'hand']);
  });
});

describe('runBuild', () => {
  let built = '';

  beforeAll(async () => {
    built = await createPipelineProject();
    const { result } = await build(built);
    expect(result.diagnostics.filter((d) => d.severity === 'error')).toEqual([]);
  }, 180_000);

  it('builds every concept from scratch', async () => {
    const { manifest } = await readManifest(built);
    expect(Object.keys(manifest.concepts).sort()).toEqual(['card', 'count-adds', 'counter', 'hand']);
    for (const entry of Object.values(manifest.concepts)) {
      expect(entry.testKey).toMatch(/^[0-9a-f]{64}$/);
      expect(entry.implKey).toMatch(/^[0-9a-f]{64}$/);
      expect(entry.approvedTestHash).toBeNull();
      expect(entry.history.map((g) => `${g.artifact}:${g.outcome}`)).toEqual(['tests:passed', 'impl:passed']);
    }
    expect(await readFileOrNull(built, modulePath('hand'))).toMatch(/^\/\/ @generated by ccc from concept hand \(key [0-9a-f]{12}\)/);
    expect(manifest.files[modulePath('hand')]).toBe(await fileHash(built, modulePath('hand')));
    expect(manifest.files['.ccc/conformance/count-adds.ts']).toMatch(/^[0-9a-f]{64}$/);
  });

  it('makes no LLM calls when nothing changed', async () => {
    const root = await copyProject(built);
    const { fake, result } = await build(root);
    expect(result.ok).toBe(true);
    expect(fake.requests).toEqual([]);
    expect(result.generated).toEqual({ tests: [], impl: [] });
  });

  it('regenerates only the implementation when Rules change', async () => {
    const root = await copyProject(built);
    const hand = PIPELINE_FILES['concepts/hand.md'] ?? '';
    await writeFileAtomic(root, 'concepts/hand.md', hand.replace('never holds the same card twice', 'never holds a card twice'));
    const { result } = await build(root);
    expect(result.ok).toBe(true);
    expect(result.generated).toEqual({ tests: [], impl: ['hand'] });
  });

  it('regenerates dependents when a dependency interface changes', async () => {
    const root = await copyProject(built);
    const card = PIPELINE_FILES['concepts/card.md'] ?? '';
    await writeFileAtomic(root, 'concepts/card.md', card.replace('  export function card(', '  export type Rank = string;\n  export function card('));
    const { result } = await build(root, { 'impl:card': () => `export type Rank = string;\n${CANNED_IMPL.card ?? ''}` });
    expect(result.ok).toBe(true);
    expect(result.generated.tests.sort()).toEqual(['card', 'count-adds', 'hand']);
    expect(result.generated.impl.sort()).toEqual(['card', 'hand']);
  });

  it('regenerates a module edited or removed since the last build', async () => {
    const root = await copyProject(built);
    await writeFileAtomic(root, modulePath('counter'), '// hand edit\n');
    await rm(path.join(root, modulePath('card')));
    const { result } = await build(root);
    expect(result.ok).toBe(true);
    expect(result.generated.impl.sort()).toEqual(['card', 'counter']);
  });

  it('never records a hand edit to a file this build did not write', async () => {
    const root = await copyProject(built);
    const edited = `${(await readFileOrNull(root, modulePath('counter'))) ?? ''}export const evil = 1;\n`;
    await writeFileAtomic(root, modulePath('counter'), edited);
    await writeFileAtomic(root, testPath('count-adds'), "it('[ex 1] x', () => {});\n");
    await build(root, {}, { only: 'hand' });
    await build(root, {}, { only: 'hand', testsOnly: true });
    const { manifest } = await readManifest(root);
    expect(manifest.files[modulePath('counter')]).not.toBe(await fileHash(root, modulePath('counter')));
    expect(manifest.files[testPath('count-adds')]).not.toBe(await fileHash(root, testPath('count-adds')));
  });

  it('does not trust a module whose regeneration failed', async () => {
    const root = await copyProject(built);
    await writeFileAtomic(root, modulePath('counter'), `${CANNED_IMPL.counter ?? ''}export const evil = 1;\n`);
    const failing = await build(root, { 'impl:counter': () => 'export const broken: number = "x";\n' });
    expect(failing.result.failed).toEqual(['counter']);
    const next = await build(root);
    expect(next.result.generated.impl).toContain('counter');
  }, 180_000);

  it('drops manifest entries for deleted concepts', async () => {
    const root = await copyProject(built);
    await rm(path.join(root, 'concepts/count-adds.md'));
    const { result } = await build(root);
    expect(result.ok).toBe(true);
    const { manifest } = await readManifest(root);
    expect(Object.keys(manifest.concepts).sort()).toEqual(['card', 'counter', 'hand']);
    expect(Object.keys(manifest.files).some((file) => file.includes('count-adds'))).toBe(false);
  });

  it('turns generator errors into failed concepts and keeps the rest', async () => {
    const root = await createPipelineProject();
    const { result } = await build(root, {
      'impl:hand': () => {
        throw new Error('529 overloaded');
      },
    });
    expect(result.failed).toEqual(['hand']);
    expect(result.skipped).toEqual(['count-adds']);
    expect(result.diagnostics.map((d) => d.message).join('\n')).toContain('generator error: 529 overloaded');
    const { manifest } = await readManifest(root);
    expect(manifest.concepts.card?.implKey).toMatch(/^[0-9a-f]{64}$/);
  }, 180_000);

  it('emits wiring and a composition root that type-check', async () => {
    const wiring = await readFileOrNull(built, '.ccc/gen/wiring.ts');
    expect(wiring).toContain("afterAction(result, 'count-adds'");
    expect(await readFileOrNull(built, '.ccc/gen/server.ts')).toContain('export async function createApp(');
    const { manifest } = await readManifest(built);
    expect(manifest.files['.ccc/gen/wiring.ts']).toMatch(/^[0-9a-f]{64}$/);
  });

  it('plans without writing on a dry run', async () => {
    const root = await createPipelineProject();
    const { fake, result } = await build(root, {}, { dryRun: true });
    expect(result.ok).toBe(true);
    expect(fake.requests).toEqual([]);
    expect(result.plan).toEqual([
      { id: 'card', tests: true, impl: true },
      { id: 'count-adds', tests: true, impl: true },
      { id: 'counter', tests: true, impl: true },
      { id: 'hand', tests: true, impl: true },
    ]);
    expect(await readFileOrNull(root, '.ccc/manifest.json')).toBeNull();
  });

  it('keeps going after a failure, skipping only dependents', async () => {
    const root = await createPipelineProject();
    const { result } = await build(root, { 'impl:hand': () => 'export const broken: number = "x";\n' });
    expect(result.ok).toBe(false);
    expect(result.failed).toEqual(['hand']);
    expect(result.skipped).toEqual(['count-adds']);
    expect(await readFileOrNull(root, modulePath('hand'))).toBeNull();
    expect(await readFileOrNull(root, modulePath('counter'))).toContain('export class Counter');
    expect(result.diagnostics.map((d) => d.message).join('\n')).toContain('implementation generation failed after 3 attempt(s)');
  }, 180_000);

  it('retries a failing attempt within one build', async () => {
    const root = await createPipelineProject();
    const good = CANNED_IMPL.counter ?? '';
    const { result } = await build(root, { 'impl:counter': (attempt) => (attempt === 1 ? good.replace('+= 1', '+= 2') : good) });
    expect(result.ok).toBe(true);
    const { manifest } = await readManifest(root);
    expect(manifest.concepts.counter?.history.at(-1)).toMatchObject({ artifact: 'impl', attempts: 2, outcome: 'passed' });
  }, 180_000);

  it('limits work to a concept and its dependencies, and can stop after tests', async () => {
    const root = await createPipelineProject();
    const { result } = await build(root, {}, { only: 'hand', testsOnly: true });
    expect(result.ok).toBe(true);
    expect(result.generated.tests.sort()).toEqual(['card', 'hand']);
    expect(result.generated.impl).toEqual([]);
    expect(await readFileOrNull(root, modulePath('hand'))).toBeNull();
  });

  it('rejects an unknown concept and concepts without examples', async () => {
    const root = await createPipelineProject();
    expect((await build(root, {}, { only: 'nope' })).result.diagnostics.map((d) => d.message)).toContain("unknown concept 'nope'");
    const counter = PIPELINE_FILES['concepts/counter.md'] ?? '';
    await writeFileAtomic(root, 'concepts/counter.md', counter.slice(0, counter.indexOf('## Examples')));
    const { result } = await build(root);
    expect(result.ok).toBe(false);
    expect(result.diagnostics.map((d) => d.message)).toContain("ccc build requires at least one example in '## Examples'");
  });
});
