import { describe, expect, it } from 'vitest';
import { compositionFiles, schemaModuleSource, serverSource, wiringSource } from '../src/compose.js';
import { collectExports } from '../src/interfaces.js';
import { concept, projectFrom } from './helpers.js';

const TALLY = concept('kind: aggregate\ninterface: |\n  export class Tally {\n    add(amount: number): void;\n  }');
const STORE = (name: string) =>
  concept(
    `kind: store\npersists: tally\ninterface: |\n  import type { Database } from '@ccc/runtime';\n  export class ${name} {\n    constructor(db: Database);\n    record(n: number): Promise<void>;\n  }`,
    '## Intent\nx\n\n## Schema\n```sql\ncreate table t (n integer);\n```\n\n## Examples\n- a\n',
  );
const API = concept('kind: endpoint\ninterface: |\n  export function createHandler(deps: object): (request: Request) => Promise<Response>;');

const files = {
  'tally.md': TALLY,
  'tally-audit.md': STORE('TallyAudit'),
  'tally-api.md': API,
  'audit-adds.md': concept('kind: sync\nwhen: tally#add\nthen: [tally-audit#record]'),
  'z-count.md': concept('kind: sync\nwhen: tally#add\nthen: [tally#add]'),
};

describe('wiringSource', () => {
  it('patches trigger methods, one block per sync in id order', () => {
    const project = projectFrom({ ...files, 'z-count.md': concept('kind: sync\nwhen: tally#add\nthen: [tally-audit#record]') });
    expect(wiringSource(project, collectExports(project))).toBe(
      [
        '// @generated by ccc. Do not edit.',
        "import { afterAction, requireScope } from '@ccc/runtime';",
        "import * as m0 from './tally.js';",
        "import * as m1 from './audit-adds.js';",
        "import * as m2 from './tally-audit.js';",
        "import * as m3 from './z-count.js';",
        '',
        '{',
        '  const original = m0.Tally.prototype.add;',
        "  m0.Tally.prototype.add = function (this: m0.Tally, ...args: Parameters<m0.Tally['add']>): ReturnType<m0.Tally['add']> {",
        "    requireScope('audit-adds');",
        '    const result = original.apply(this, args);',
        "    return afterAction(result, 'audit-adds', async (settled, scope) => {",
        "      await m1.handle({ target: this, args, result: settled }, { tallyAudit: scope.resolve<m2.TallyAudit>('tally-audit', 'audit-adds') });",
        '    });',
        '  };',
        '}',
        '',
        '{',
        '  const original = m0.Tally.prototype.add;',
        "  m0.Tally.prototype.add = function (this: m0.Tally, ...args: Parameters<m0.Tally['add']>): ReturnType<m0.Tally['add']> {",
        "    requireScope('z-count');",
        '    const result = original.apply(this, args);',
        "    return afterAction(result, 'z-count', async (settled, scope) => {",
        "      await m3.handle({ target: this, args, result: settled }, { tallyAudit: scope.resolve<m2.TallyAudit>('tally-audit', 'z-count') });",
        '    });',
        '  };',
        '}',
        '',
      ].join('\n'),
    );
  });

  it('is an empty module without syncs', () => {
    const project = projectFrom({ 'tally.md': TALLY });
    expect(wiringSource(project, collectExports(project))).toBe('// @generated by ccc. Do not edit.\nexport {};\n');
  });
});

describe('serverSource', () => {
  it('builds adapters, binds them, and loads endpoints lazily', () => {
    const source = serverSource(projectFrom(files));
    expect(source).toContain("import './wiring.js';");
    expect(source).toContain("import * as a0 from './tally-audit.js';");
    expect(source).toContain('    tallyAudit: new a0.TallyAudit(db),');
    expect(source).toContain("    'tally-audit': container.tallyAudit,");
    expect(source).toContain("    'tally-api': async () => (await import('./tally-api.js')).createHandler(container),");
    expect(source).toContain('const response = await handler(request.clone());');
  });
});

describe('compositionFiles', () => {
  it('lists every generated composition file', () => {
    const project = projectFrom(files);
    const written = compositionFiles(project, collectExports(project));
    expect(written.map(([file]) => file)).toEqual([
      '.ccc/gen/wiring.ts',
      '.ccc/gen/server.ts',
      '.ccc/gen/main.ts',
      '.ccc/gen/schema.sql',
      '.ccc/gen/schema.ts',
    ]);
    expect(written[4]?.[1]).toBe(schemaModuleSource('-- tally-audit\ncreate table t (n integer);\n'));
    expect(schemaModuleSource('x')).toBe('// @generated by ccc. Do not edit.\nexport const schemaSql = "x";\n');
  });
});
