import { describe, expect, it } from 'vitest';
import type { Config } from '../src/config.js';
import { emitDeterministicFiles } from '../src/emit.js';
import { readFileOrNull, writeFileAtomic } from '../src/fsutil.js';
import { checkModuleOnDisk, generateImpl } from '../src/implgen.js';
import { generatedHeader, modulePath, testPath } from '../src/layout.js';
import { FakeGenerator } from './fake-generator.js';
import { CANNED_IMPL, CANNED_TESTS, createPipelineProject, pipelineContext, pipelineResponder, type Overrides } from './pipeline-fixture.js';

async function ready(overrides: Overrides = {}, config: Partial<Config> = {}) {
  const root = await createPipelineProject();
  const fake = new FakeGenerator(pipelineResponder(overrides));
  const ctx = await pipelineContext(root, fake, config);
  await emitDeterministicFiles(root, ctx.project, ctx.exportsByConcept);
  for (const id of ['card', 'hand']) {
    await writeFileAtomic(root, testPath(id), CANNED_TESTS[id] ?? '');
  }
  await writeFileAtomic(root, modulePath('card'), `${generatedHeader('card', 'k'.repeat(12))}\n${CANNED_IMPL.card}`);
  const hand = ctx.project.concepts.get('hand');
  if (hand === undefined) throw new Error('fixture');
  return { root, fake, ctx, hand };
}

describe('generateImpl', () => {
  it('writes a passing module with a header', async () => {
    const { root, ctx, hand } = await ready();
    const outcome = await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'abcdef0123456789', commit: true });
    expect(outcome.record).toMatchObject({ artifact: 'impl', attempts: 1, outcome: 'passed' });
    const written = await readFileOrNull(root, modulePath('hand'));
    expect(written).toBe(`// @generated by ccc from concept hand (key abcdef012345). Do not edit.\n${CANNED_IMPL.hand}`);
    expect(outcome.source).toBe(written);
  });

  it('feeds test failures back and accepts a later attempt', async () => {
    const good = CANNED_IMPL.hand ?? '';
    const { fake, ctx, hand } = await ready({
      'impl:hand': (attempt) => (attempt === 1 ? good.replace('throw new DuplicateCard', 'return; throw new DuplicateCard') : good),
    });
    const outcome = await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'k'.repeat(16), commit: true });
    expect(outcome.record.attempts).toBe(2);
    expect(fake.requests[1]?.messages[1]).toContain('test failed: [ex 2] rejects a duplicate card');
  });

  it('starts on the configured model and escalates along the ladder', async () => {
    const good = CANNED_IMPL.hand ?? '';
    const { fake, ctx, hand } = await ready(
      { 'impl:hand': (attempt) => (attempt === 1 ? good.replace('throw new DuplicateCard', 'return; throw new DuplicateCard') : good) },
      { escalateAfter: 1 },
    );
    const outcome = await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'k'.repeat(16), commit: true });
    expect(fake.requests.map((request) => request.model)).toEqual(['claude-haiku-4-5', 'claude-sonnet-5']);
    expect(outcome.record).toMatchObject({ model: 'claude-sonnet-5', attempts: 2, escalations: 1, outcome: 'passed' });
  });

  it('puts the previous module back while waiting for the next attempt', async () => {
    const good = CANNED_IMPL.hand ?? '';
    const seen: (string | null)[] = [];
    const holder = { root: '' };
    const { root, ctx, hand } = await ready({
      'impl:hand': async (attempt) => {
        if (attempt === 1) {
          return good.replace('throw new DuplicateCard', 'return; throw new DuplicateCard');
        }
        seen.push(await readFileOrNull(holder.root, modulePath('hand')));
        return good;
      },
    });
    holder.root = root;
    await writeFileAtomic(root, modulePath('hand'), '// previous good version\n');
    const outcome = await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'k'.repeat(16), commit: true });
    expect(outcome.record.attempts).toBe(2);
    expect(seen).toEqual(['// previous good version\n']);
  });

  it('rejects disallowed imports without writing them', async () => {
    const good = CANNED_IMPL.hand ?? '';
    const { fake, ctx, hand } = await ready({
      'impl:hand': (attempt) => (attempt === 1 ? `import fs from 'node:fs';\n${good}` : good),
    });
    await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'k'.repeat(16), commit: true });
    expect(fake.requests[1]?.messages[1]).toContain("package 'node:fs' is not allowed here");
  });

  it('rejects an extra exported value before running checks', async () => {
    const good = CANNED_IMPL.hand ?? '';
    const { ctx, hand } = await ready({ 'impl:hand': () => `${good}\nexport const extra = 1;\n` });
    const outcome = await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'k'.repeat(16), commit: true });
    expect(outcome.source).toBeNull();
    expect(outcome.problems).toEqual(['exports extra, which is not in the interface']);
  });

  it('fails conformance when an exported type differs from the interface', async () => {
    const { ctx } = await ready({
      'impl:card': () => (CANNED_IMPL.card ?? '').replace('  readonly suit: string;\n}', '  readonly suit: string;\n  readonly extra?: number;\n}'),
    });
    const card = ctx.project.concepts.get('card');
    if (card === undefined) throw new Error('fixture');
    const outcome = await generateImpl(ctx, card, CANNED_TESTS.card ?? '', { key: 'k'.repeat(16), commit: true });
    expect(outcome.source).toBeNull();
    expect(outcome.problems.join('\n')).toContain('Card differs from the interface');
  });

  it('rejects exports the interface does not declare, including types', async () => {
    const good = CANNED_IMPL.hand ?? '';
    const { fake, ctx, hand } = await ready({
      'impl:hand': (attempt) => (attempt === 1 ? `${good}\nexport type Extra = string;\n` : good),
    });
    await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'k'.repeat(16), commit: true });
    expect(fake.requests[1]?.messages[1]).toContain('exports Extra, which is not in the interface');
  });

  it('restores the previous module after exhausting attempts', async () => {
    const { root, ctx, hand } = await ready({ 'impl:hand': () => 'export const broken: number = "x";\n' });
    await writeFileAtomic(root, modulePath('hand'), '// previous good version\n');
    const outcome = await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'k'.repeat(16), commit: true });
    expect(outcome.source).toBeNull();
    expect(outcome.record).toMatchObject({ attempts: 3, outcome: 'failed' });
    expect(await readFileOrNull(root, modulePath('hand'))).toBe('// previous good version\n');
  });

  it('leaves the file untouched when commit is false', async () => {
    const { root, ctx, hand } = await ready();
    const outcome = await generateImpl(ctx, hand, CANNED_TESTS.hand ?? '', { key: 'k'.repeat(16), commit: false });
    expect(outcome.source).toContain('export class Hand');
    expect(await readFileOrNull(root, modulePath('hand'))).toBeNull();
  });
});

describe('checkModuleOnDisk', () => {
  it('passes a good module and reports a failing one', async () => {
    const { root, ctx } = await ready();
    const card = ctx.project.concepts.get('card');
    if (card === undefined) throw new Error('fixture');
    expect(await checkModuleOnDisk(ctx, card)).toEqual([]);
    await writeFileAtomic(root, modulePath('card'), (CANNED_IMPL.card ?? '').replace('return { rank, suit };', 'return { rank: suit, suit: rank };'));
    expect((await checkModuleOnDisk(ctx, card)).join('\n')).toContain('test failed: [ex 1] builds a card');
    await writeFileAtomic(root, modulePath('card'), CANNED_IMPL.card ?? '');
    await writeFileAtomic(root, testPath('card'), (CANNED_TESTS.card ?? '').replace("it('[ex 2]", "it.skip('[ex 2]"));
    expect(await checkModuleOnDisk(ctx, card)).toEqual(['test skipped: [ex 2] compares cards by rank and suit']);
  });
});
