import { describe, expect, it } from 'vitest';
import { collectExports, emitInterfaces, exportsOf, interfacePath, relativeImport } from '../src/interfaces.js';
import { concept, projectFrom } from './helpers.js';

describe('exportsOf', () => {
  it('lists exported names, functions, and class methods', () => {
    const info = exportsOf(`
export class Hand {
  constructor(cards?: readonly string[]);
  add(card: string): void;
  size(): number;
  readonly label: string;
}
export class DuplicateCard extends Error {}
export function deal(): void;
export function deal(count: number): void;
export interface Card { rank: string }
export type Suit = 'S' | 'H';
export enum Color { Red, Black }
export const MAX: number;
class Hidden {}
function hidden(): void;
`);
    expect(info.names).toEqual(['Hand', 'DuplicateCard', 'deal', 'Card', 'Suit', 'Color', 'MAX']);
    expect(info.functions).toEqual(['deal']);
    expect(info.classMethods.get('Hand')).toEqual(['add', 'size']);
    expect(info.classMethods.get('DuplicateCard')).toEqual([]);
  });
});

describe('paths', () => {
  it('maps ids to d.ts paths and relative imports', () => {
    expect(interfacePath('game.player.hand')).toBe('game/player/hand.d.ts');
    expect(relativeImport('game.player.hand', 'card')).toBe('../../card.js');
    expect(relativeImport('game', 'game.player')).toBe('./game/player.js');
    expect(relativeImport('game.deck', 'game.player')).toBe('./player.js');
  });
});

const CARD = concept('kind: value\ninterface: |\n  export interface Card { readonly rank: string }\n  export function card(rank: string): Card;');

describe('emitInterfaces', () => {
  it('emits a header, imports from dependencies, then the interface', () => {
    const project = projectFrom({
      'card.md': CARD,
      'game.md': concept('kind: aggregate\ninterface: export class Game {}'),
      'game/hand.md': concept(
        'kind: collection\nof: card\ninterface: |\n  export class Hand {\n    add(card: Card): void;\n  }',
      ),
    });
    const { files, diagnostics } = emitInterfaces(project, collectExports(project));
    expect(diagnostics).toEqual([]);
    const hand = files.find((f) => f.id === 'game.hand');
    expect(hand?.path).toBe('game/hand.d.ts');
    expect(hand?.conceptFile).toBe('concepts/game/hand.md');
    expect(hand?.headerLines).toBe(2);
    expect(hand?.content).toBe(
      [
        '// @generated by ccc from concept game.hand. Do not edit.',
        "import { Card, card } from '../card.js';",
        'export class Hand {',
        '  add(card: Card): void;',
        '}',
        '',
      ].join('\n'),
    );
    const game = files.find((f) => f.id === 'game');
    expect(game?.content).toContain("import { Hand } from './game/hand.js';");
  });

  it('skips syncs and dependencies with no exports', () => {
    const project = projectFrom({
      'card.md': CARD,
      'deal.md': concept('kind: sync\nwhen: card#card\nthen: [card#card]'),
    });
    const { files } = emitInterfaces(project, collectExports(project));
    expect(files.map((f) => f.id)).toEqual(['card']);
  });

  it('reports export name collisions', () => {
    const project = projectFrom({
      'a.md': concept('kind: value\ninterface: export type Id = string;'),
      'b.md': concept('kind: value\ninterface: export type Id = number;'),
      'c.md': concept('kind: value\nuses: [a, b]\ninterface: export type C = Id;'),
      'd.md': concept('kind: value\nuses: [a]\ninterface: export type Id = boolean;'),
    });
    const { diagnostics } = emitInterfaces(project, collectExports(project));
    expect(diagnostics.map((d) => `${d.file}: ${d.message}`)).toEqual([
      "concepts/c.md: 'Id' is exported by both dependencies a and b",
      "concepts/d.md: 'Id' is exported by both d and its dependency a",
    ]);
  });
});
