import { describe, expect, it } from 'vitest';
import {
  checkInterfaces,
  collectExports,
  emitInterfaces,
  exportsOf,
  interfacePath,
  interfaceProblems,
  relativeImport,
} from '../src/interfaces.js';
import { concept, projectFrom } from './helpers.js';

describe('exportsOf', () => {
  it('lists exported names, functions, and class methods', () => {
    const info = exportsOf(`
export class Hand {
  constructor(cards?: readonly string[]);
  add(card: string): void;
  size(): number;
  readonly label: string;
}
export class DuplicateCard extends Error {}
export function deal(): void;
export function deal(count: number): void;
export interface Card { rank: string }
export type Suit = 'S' | 'H';
export enum Color { Red, Black }
export const MAX: number;
class Hidden {}
function hidden(): void;
`);
    expect(info.names).toEqual(['Hand', 'DuplicateCard', 'deal', 'Card', 'Suit', 'Color', 'MAX']);
    expect(info.functions).toEqual(['deal']);
    expect(info.classMethods.get('Hand')).toEqual(['add', 'size']);
    expect(info.classMethods.get('DuplicateCard')).toEqual([]);
  });
});

describe('exportsOf types', () => {
  it('lists non-generic interfaces and type aliases as types', () => {
    const info = exportsOf('export interface Card { rank: string }\nexport type Suit = string;\nexport type Box<T> = T[];\nexport class Hand {}\nexport function deal(): void;');
    expect(info.types).toEqual(['Card', 'Suit']);
  });
});

describe('paths', () => {
  it('maps ids to d.ts paths and relative imports', () => {
    expect(interfacePath('game.player.hand')).toBe('game/player/hand.d.ts');
    expect(relativeImport('game.player.hand', 'card')).toBe('../../card.js');
    expect(relativeImport('game', 'game.player')).toBe('./game/player.js');
    expect(relativeImport('game.deck', 'game.player')).toBe('./player.js');
  });
});

const CARD = concept('kind: value\ninterface: |\n  export interface Card { readonly rank: string }\n  export function card(rank: string): Card;');

describe('emitInterfaces', () => {
  it('emits a header, imports from dependencies, then the interface', () => {
    const project = projectFrom({
      'card.md': CARD,
      'game.md': concept('kind: aggregate\ninterface: |\n  export class Game {\n    hand(): Hand;\n  }'),
      'game/hand.md': concept(
        'kind: collection\nof: card\ninterface: |\n  export class Hand {\n    add(card: Card): void;\n  }',
      ),
    });
    const { files, diagnostics } = emitInterfaces(project, collectExports(project));
    expect(diagnostics).toEqual([]);
    const hand = files.find((f) => f.id === 'game.hand');
    expect(hand?.path).toBe('game/hand.d.ts');
    expect(hand?.conceptFile).toBe('concepts/game/hand.md');
    expect(hand?.headerLines).toBe(2);
    expect(hand?.content).toBe(
      [
        '// @generated by ccc from concept game.hand. Do not edit.',
        "import { Card, card } from '../card.js';",
        'export class Hand {',
        '  add(card: Card): void;',
        '}',
        '',
      ].join('\n'),
    );
    const game = files.find((f) => f.id === 'game');
    expect(game?.content).toContain("import { Hand } from './game/hand.js';");
  });

  it('emits synthesized interfaces for syncs', () => {
    const project = projectFrom({
      'card.md': CARD,
      'deal.md': concept('kind: sync\nwhen: card#card\nthen: [card#card]'),
    });
    const { files, diagnostics } = emitInterfaces(project, collectExports(project));
    expect(diagnostics).toEqual([]);
    expect(files.map((f) => f.id)).toEqual(['card', 'deal']);
    const deal = files.find((f) => f.id === 'deal');
    expect(deal?.path).toBe('deal.d.ts');
    expect(deal?.headerLines).toBe(0);
    expect(deal?.content).toContain('export function handle(event: SyncEvent, targets: SyncTargets): Promise<void>;');
  });

  it('reports collisions only among referenced dependency exports', () => {
    const project = projectFrom({
      'a.md': concept('kind: value\ninterface: export type Id = string;'),
      'b.md': concept('kind: value\ninterface: export type Id = number;'),
      'c.md': concept('kind: value\nuses: [a, b]\ninterface: export type C = Id;'),
      'd.md': concept('kind: value\nuses: [a]\ninterface: export type Id = boolean;'),
    });
    const { files, diagnostics } = emitInterfaces(project, collectExports(project));
    expect(diagnostics.map((d) => `${d.file}: ${d.message}`)).toEqual([
      "concepts/c.md: 'Id' is exported by both dependencies a and b",
    ]);
    expect(files.find((f) => f.id === 'd')?.content).not.toContain('import');
  });

  it('imports only the names an interface references', () => {
    const project = projectFrom({
      'game.md': concept('kind: aggregate\ninterface: |\n  export class Game {\n    deck(): Deck;\n  }'),
      'game/deck.md': concept('kind: value\ninterface: |\n  export class Empty extends Error {}\n  export class Deck {}'),
      'game/seats.md': concept('kind: value\ninterface: |\n  export class Empty extends Error {}\n  export class Seats {}'),
    });
    const { files, diagnostics } = emitInterfaces(project, collectExports(project));
    expect(diagnostics).toEqual([]);
    const game = files.find((f) => f.id === 'game');
    expect(game?.content).toContain("import { Deck } from './game/deck.js';");
    expect(game?.content).not.toContain('Empty');
    expect(game?.content).not.toContain('./game/seats.js');
  });
});

describe('interfaceProblems / checkInterfaces', () => {
  it('accepts an interface with exports and no imports', () => {
    expect(interfaceProblems('export class A {}')).toEqual([]);
  });
  it('rejects imports, ambient modules, global augmentation, and interfaces without exports', () => {
    expect(interfaceProblems("import { S } from './secret.js';\nexport type A = S;")).toEqual([
      'interface line 1: interfaces cannot import modules; list the concept in uses instead',
    ]);
    expect(interfaceProblems('export class A {}\ndeclare global {\n  interface Leaked {}\n}')).toEqual([
      'interface line 2: interfaces cannot declare global or ambient modules',
    ]);
    expect(interfaceProblems("export class A {}\ndeclare module 'x' {}")).toEqual([
      'interface line 2: interfaces cannot declare global or ambient modules',
    ]);
    expect(interfaceProblems('declare class Card {}')).toEqual(['interface must export at least one declaration']);
  });
  it('allows type-only imports from @ccc/runtime and nothing else', () => {
    expect(interfaceProblems("import type { Database } from '@ccc/runtime';\nexport class S {\n  constructor(db: Database);\n}")).toEqual([]);
    expect(interfaceProblems("import { Database } from '@ccc/runtime';\nexport class S {}")).toEqual([
      'interface line 1: interfaces cannot import modules; list the concept in uses instead',
    ]);
    expect(interfaceProblems("import type { X } from 'pg';\nexport class S {}")).toEqual([
      'interface line 1: interfaces cannot import modules; list the concept in uses instead',
    ]);
  });

  it('reports problems on the concept file and ignores syncs', () => {
    const project = projectFrom({
      'card.md': concept('kind: value\ninterface: declare class Card {}'),
      'deal.md': concept('kind: sync\nwhen: card#a\nthen: [card#b]'),
    });
    expect(checkInterfaces(project).map((d) => `${d.file}: ${d.message}`)).toEqual([
      'concepts/card.md: interface must export at least one declaration',
    ]);
  });
});
