import { describe, expect, it } from 'vitest';
import {
  conformancePath,
  conformanceSource,
  generatedHeader,
  handwrittenModuleSource,
  interfaceFile,
  interfacePath,
  modulePath,
  ownModuleSpecifier,
  relativeImport,
  testPath,
} from '../src/layout.js';
import * as interfaces from '../src/interfaces.js';

describe('paths', () => {
  it('maps concept ids to generated file paths', () => {
    expect(modulePath('game.player.hand')).toBe('.ccc/gen/game/player/hand.ts');
    expect(testPath('game.player.hand')).toBe('.ccc/gen/game/player/hand.test.ts');
    expect(interfaceFile('card')).toBe('.ccc/interfaces/card.d.ts');
    expect(interfacePath('game.hand')).toBe('game/hand.d.ts');
    expect(conformancePath('game.hand')).toBe('.ccc/conformance/game/hand.ts');
    expect(ownModuleSpecifier('game.player.hand')).toBe('./hand.js');
    expect(relativeImport('game.player.hand', 'card')).toBe('../../card.js');
  });

  it('keeps the old exports on interfaces.ts', () => {
    expect(interfaces.relativeImport).toBe(relativeImport);
    expect(interfaces.interfacePath).toBe(interfacePath);
  });
});

describe('sources', () => {
  it('writes a header with a short key', () => {
    expect(generatedHeader('card', 'abcdef0123456789')).toBe(
      '// @generated by ccc from concept card (key abcdef012345). Do not edit.',
    );
  });

  it('writes conformance checks relative to .ccc', () => {
    expect(conformanceSource('card')).toBe(
      [
        '// @generated by ccc from concept card. Do not edit.',
        "import * as impl from '../gen/card.js';",
        "import type * as iface from '../interfaces/card.js';",
        '',
        'export const conforms: typeof iface = impl;',
        'type Extra = Exclude<keyof typeof impl, keyof typeof iface>;',
        'export const noExtraExports: [Extra] extends [never] ? true : Extra = true;',
        '',
      ].join('\n'),
    );
    expect(conformanceSource('game.player.hand')).toContain("import * as impl from '../../../gen/game/player/hand.js';");
  });

  it('re-exports handwritten sources', () => {
    expect(handwrittenModuleSource('user', 'handwritten/user.ts')).toBe(
      "// @generated by ccc from concept user. Do not edit.\nexport * from '../../handwritten/user.js';\n",
    );
    expect(handwrittenModuleSource('game.player', 'handwritten/player.ts')).toContain(
      "export * from '../../../handwritten/player.js';",
    );
  });
});
