import { describe, expect, it } from 'vitest';
import { collectExports } from '../src/interfaces.js';
import { syncInterface, targetKey } from '../src/synciface.js';
import { concept, projectFrom } from './helpers.js';

const HAND = concept('kind: collection\nof: card\ninterface: |\n  export class Hand {\n    add(card: Card): void;\n  }');
const CARD = concept(
  'kind: value\ninterface: |\n  export interface Card { readonly rank: string }\n  export function card(rank: string): Card;\n  export function sameCard(a: Card, b: Card): boolean;',
);
const COUNTER = concept('kind: entity\ninterface: |\n  export class Counter {\n    increment(): void;\n    value(): number;\n  }');

function synthesize(files: Record<string, string>, id: string) {
  const project = projectFrom(files);
  const sync = project.concepts.get(id);
  if (sync === undefined) throw new Error('fixture');
  return syncInterface(sync, collectExports(project));
}

describe('targetKey', () => {
  it('camel-cases concept ids', () => {
    expect(targetKey('game.players')).toBe('gamePlayers');
    expect(targetKey('game-store')).toBe('gameStore');
    expect(targetKey('card')).toBe('card');
  });
});

describe('syncInterface', () => {
  it('types a method trigger and class targets', () => {
    const { source, diagnostics } = synthesize(
      {
        'card.md': CARD,
        'hand.md': HAND,
        'counter.md': COUNTER,
        'count-adds.md': concept('kind: sync\nwhen: hand#add\nthen: [counter#increment]'),
      },
      'count-adds',
    );
    expect(diagnostics).toEqual([]);
    expect(source).toBe(
      [
        '// @generated by ccc from sync count-adds. Do not edit.',
        "import { Counter } from './counter.js';",
        "import { Hand } from './hand.js';",
        '',
        'export interface SyncEvent {',
        '  readonly target: Hand;',
        "  readonly args: Parameters<Hand['add']>;",
        "  readonly result: Awaited<ReturnType<Hand['add']>>;",
        '}',
        'export interface SyncTargets {',
        '  readonly counter: Counter;',
        '}',
        'export function handle(event: SyncEvent, targets: SyncTargets): Promise<void>;',
        '',
      ].join('\n'),
    );
  });

  it('types a function trigger and module targets', () => {
    const { source } = synthesize(
      { 'card.md': CARD, 'deal.md': concept('kind: sync\nwhen: card#card\nthen: [card#sameCard]') },
      'deal',
    );
    expect(source).toBe(
      [
        '// @generated by ccc from sync deal. Do not edit.',
        "import { card } from './card.js';",
        "import * as cardModule from './card.js';",
        '',
        'export interface SyncEvent {',
        '  readonly args: Parameters<typeof card>;',
        '  readonly result: Awaited<ReturnType<typeof card>>;',
        '}',
        'export interface SyncTargets {',
        '  readonly card: typeof cardModule;',
        '}',
        'export function handle(event: SyncEvent, targets: SyncTargets): Promise<void>;',
        '',
      ].join('\n'),
    );
  });

  it('reports two concepts whose primary classes share a name', () => {
    const { diagnostics } = synthesize(
      {
        'card.md': CARD,
        'hand.md': HAND,
        'game.md': concept('kind: aggregate\ninterface: export class Game {}'),
        'game/hand.md': HAND,
        'deal.md': concept('kind: sync\nwhen: hand#add\nthen: [game.hand#add]'),
      },
      'deal',
    );
    expect(diagnostics.map((d) => d.message)).toEqual([
      "sync needs 'Hand' from both hand and game.hand; rename one of them",
    ]);
  });

  it('returns no source when a referenced concept is unknown', () => {
    expect(synthesize({ 'card.md': CARD, 'deal.md': concept('kind: sync\nwhen: nope#x\nthen: [card#card]') }, 'deal').source).toBeNull();
  });
});
