import { combinedSchema } from './adapters.js';
import { parseActionRef, type ConceptId } from './ids.js';
import type { ExportInfo } from './interfaces.js';
import type { Project } from './load.js';
import type { Concept } from './parse.js';
import { targetKey } from './synciface.js';
import { primaryClassName } from './syncs.js';

export const WIRING_FILE = '.ccc/gen/wiring.ts';
export const SERVER_FILE = '.ccc/gen/server.ts';
export const MAIN_FILE = '.ccc/gen/main.ts';
export const SCHEMA_SQL_FILE = '.ccc/gen/schema.sql';
export const SCHEMA_TS_FILE = '.ccc/gen/schema.ts';

const HEADER = '// @generated by ccc. Do not edit.';

// Declarations that stand in for the generated schema and server modules
// when tests are type-checked against interfaces only.
export const SCHEMA_DECLARATION = 'export declare const schemaSql: string;\n';
export const SERVER_DECLARATION = [
  "import type { Database } from '@ccc/runtime';",
  'export type Handler = (request: Request) => Promise<Response>;',
  'export interface AppOptions {',
  '  readonly endpoints?: readonly string[];',
  '}',
  'export declare function createApp(db: Database, options?: AppOptions): Promise<Handler>;',
  '',
].join('\n');

function modulePathFromGen(id: ConceptId): string {
  return `./${id.split('.').join('/')}.js`;
}

function byId(a: Concept, b: Concept): number {
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

// Each sync patches its trigger's prototype method: the original runs, then
// the handler is deferred into the current scope with its targets resolved
// (instances from the scope, function-action modules as namespaces).
export function wiringSource(project: Project, exportsByConcept: ReadonlyMap<ConceptId, ExportInfo>): string {
  const syncs = [...project.concepts.values()].filter((c) => c.frontmatter.kind === 'sync').sort(byId);
  if (syncs.length === 0) {
    return `${HEADER}\nexport {};\n`;
  }
  const aliases = new Map<ConceptId, string>();
  const alias = (id: ConceptId): string => {
    const known = aliases.get(id);
    if (known !== undefined) {
      return known;
    }
    const created = `m${aliases.size}`;
    aliases.set(id, created);
    return created;
  };
  const blocks: string[] = [];
  for (const sync of syncs) {
    const fm = sync.frontmatter;
    if (fm.kind !== 'sync') {
      continue;
    }
    const when = parseActionRef(fm.when);
    const trigger = `${alias(when.conceptId)}.${primaryClassName(when.conceptId)}`;
    const handler = alias(sync.id);
    const actionsByTarget = new Map<ConceptId, string[]>();
    for (const ref of fm.then) {
      const { conceptId, member } = parseActionRef(ref);
      actionsByTarget.set(conceptId, [...(actionsByTarget.get(conceptId) ?? []), member]);
    }
    const targets = [...actionsByTarget].map(([conceptId, members]) => {
      const info = exportsByConcept.get(conceptId);
      const key = targetKey(conceptId);
      if (members.every((member) => !(info?.functions.includes(member) ?? false))) {
        return `${key}: scope.resolve<${alias(conceptId)}.${primaryClassName(conceptId)}>('${conceptId}', '${sync.id}')`;
      }
      return `${key}: ${alias(conceptId)}`;
    });
    blocks.push(
      [
        '{',
        `  const original = ${trigger}.prototype.${when.member};`,
        `  ${trigger}.prototype.${when.member} = function (this: ${trigger}, ...args: Parameters<${trigger}['${when.member}']>): ReturnType<${trigger}['${when.member}']> {`,
        '    const result = original.apply(this, args);',
        `    return afterAction(result, '${sync.id}', async (settled, scope) => {`,
        `      await ${handler}.handle({ target: this, args, result: settled }, { ${targets.join(', ')} });`,
        '    });',
        '  };',
        '}',
        '',
      ].join('\n'),
    );
  }
  const imports = [...aliases].map(([id, name]) => `import * as ${name} from '${modulePathFromGen(id)}';`);
  return [HEADER, "import { afterAction } from '@ccc/runtime';", ...imports, '', ...blocks].join('\n');
}

export function serverSource(project: Project): string {
  const concepts = [...project.concepts.values()].sort(byId);
  const adapters = concepts.filter((c) => c.frontmatter.kind === 'store' || c.frontmatter.kind === 'auth');
  const endpoints = concepts.filter((c) => c.frontmatter.kind === 'endpoint');
  return [
    HEADER,
    "import { isUnmatched, withScope, type Database } from '@ccc/runtime';",
    "import './wiring.js';",
    ...adapters.map((c, index) => `import * as a${index} from '${modulePathFromGen(c.id)}';`),
    '',
    'export type Handler = (request: Request) => Promise<Response>;',
    '',
    'export interface AppOptions {',
    '  readonly endpoints?: readonly string[];',
    '}',
    '',
    'export async function createApp(db: Database, options: AppOptions = {}): Promise<Handler> {',
    '  const container = {',
    '    db,',
    ...adapters.map((c, index) => `    ${targetKey(c.id)}: new a${index}.${primaryClassName(c.id)}(db),`),
    '  };',
    '  const singletons = {',
    ...adapters.map((c) => `    '${c.id}': container.${targetKey(c.id)},`),
    '  };',
    '  const loaders: Record<string, () => Promise<Handler>> = {',
    ...endpoints.map(
      (c) => `    '${c.id}': async () => (await import('${modulePathFromGen(c.id)}')).createHandler(container),`,
    ),
    '  };',
    '  const handlers: Handler[] = [];',
    '  for (const [id, load] of Object.entries(loaders)) {',
    '    if (options.endpoints === undefined || options.endpoints.includes(id)) {',
    '      handlers.push(await load());',
    '    }',
    '  }',
    '  return async (request) =>',
    '    withScope(singletons, async () => {',
    '      for (const handler of handlers) {',
    '        const response = await handler(request.clone());',
    '        if (!isUnmatched(response)) {',
    '          return response;',
    '        }',
    '      }',
    "      return new Response('Not Found', { status: 404 });",
    '    });',
    '}',
    '',
  ].join('\n');
}

export const MAIN_SOURCE = [
  HEADER,
  "import { serve } from '@hono/node-server';",
  "import { pgDatabase } from '@ccc/runtime';",
  "import pg from 'pg';",
  "import { createApp } from './server.js';",
  '',
  'const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });',
  "serve({ fetch: await createApp(pgDatabase(pool)), port: Number(process.env.PORT ?? '3000') });",
  '',
].join('\n');

export function schemaModuleSource(sql: string): string {
  return `${HEADER}\nexport const schemaSql = ${JSON.stringify(sql)};\n`;
}

export function compositionFiles(project: Project, exportsByConcept: ReadonlyMap<ConceptId, ExportInfo>): [string, string][] {
  const sql = combinedSchema(project);
  return [
    [WIRING_FILE, wiringSource(project, exportsByConcept)],
    [SERVER_FILE, serverSource(project)],
    [MAIN_FILE, MAIN_SOURCE],
    [SCHEMA_SQL_FILE, sql],
    [SCHEMA_TS_FILE, schemaModuleSource(sql)],
  ];
}
