import path from 'node:path';
import type { ConceptId } from './ids.js';

export const CCC_DIR = '.ccc';
export const GEN_DIR = '.ccc/gen';
export const INTERFACES_DIR = '.ccc/interfaces';
export const CONFORMANCE_DIR = '.ccc/conformance';
export const SCRATCH_DIR = '.ccc/.tmp';
export const MANIFEST_FILE = '.ccc/manifest.json';
export const CCC_PACKAGE_JSON = '{\n  "type": "module"\n}\n';
export const CCC_GITIGNORE = '.tmp/\n';

function idPath(id: ConceptId): string {
  return id.split('.').join('/');
}

export function interfacePath(id: ConceptId): string {
  return `${idPath(id)}.d.ts`;
}

// Specifier from one concept's module to another's. Generated modules and
// interfaces share the same tree shape, so one function serves both.
export function relativeImport(from: ConceptId, to: ConceptId): string {
  const rel = path.posix
    .relative(path.posix.dirname(interfacePath(from)), interfacePath(to))
    .replace(/\.d\.ts$/, '.js');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

export function modulePath(id: ConceptId): string {
  return `${GEN_DIR}/${idPath(id)}.ts`;
}

export function testPath(id: ConceptId): string {
  return `${GEN_DIR}/${idPath(id)}.test.ts`;
}

export function interfaceFile(id: ConceptId): string {
  return `${INTERFACES_DIR}/${interfacePath(id)}`;
}

export function conformancePath(id: ConceptId): string {
  return `${CONFORMANCE_DIR}/${idPath(id)}.ts`;
}

// The concept's interface, placed beside its generated module so the
// interface's relative imports resolve to the real generated dependencies.
export function contractPath(id: ConceptId): string {
  return `${GEN_DIR}/${idPath(id)}.contract.d.ts`;
}

export function ownModuleSpecifier(id: ConceptId): string {
  return `./${id.split('.').at(-1) ?? id}.js`;
}

export function generatedHeader(id: ConceptId, key: string): string {
  return `// @generated by ccc from concept ${id} (key ${key.slice(0, 12)}). Do not edit.`;
}

// Compile-time proof that a generated module matches its interface: its
// value exports must be assignable to the contract's, with none extra. The
// contract (not .ccc/interfaces) is used so dependency types are the same
// generated classes the module uses; classes with private members compare
// nominally.
export function conformanceSource(id: ConceptId): string {
  const up = '../'.repeat(id.split('.').length);
  const target = idPath(id);
  return [
    `// @generated by ccc from concept ${id}. Do not edit.`,
    `import * as impl from '${up}gen/${target}.js';`,
    `import type * as iface from '${up}gen/${target}.contract.js';`,
    '',
    'export const conforms: typeof iface = impl;',
    'type Extra = Exclude<keyof typeof impl, keyof typeof iface>;',
    'export const noExtraExports: [Extra] extends [never] ? true : Extra = true;',
    '',
  ].join('\n');
}

export function handwrittenModuleSource(id: ConceptId, source: string): string {
  const rel = path.posix.relative(path.posix.dirname(modulePath(id)), source.replace(/\.ts$/, '.js'));
  return [
    `// @generated by ccc from concept ${id}. Do not edit.`,
    `export * from '${rel.startsWith('.') ? rel : `./${rel}`}';`,
    '',
  ].join('\n');
}
