import { error, type Diagnostic } from './diagnostics.js';
import { parseActionRef, type ConceptId } from './ids.js';
import type { ExportInfo } from './interfaces.js';
import { relativeImport } from './layout.js';
import type { Concept } from './parse.js';
import { primaryClassName } from './syncs.js';

export interface SyncInterface {
  source: string | null;
  diagnostics: Diagnostic[];
}

export function targetKey(id: ConceptId): string {
  return id
    .split(/[.-]/)
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');
}

// Builds the interface a sync handler implements, from the `when` and `then`
// actions. Method actions use the concept's primary class; function actions
// use the function (trigger) or the module namespace (targets).
export function syncInterface(sync: Concept, exportsByConcept: ReadonlyMap<ConceptId, ExportInfo>): SyncInterface {
  const fm = sync.frontmatter;
  if (fm.kind !== 'sync') {
    return { source: null, diagnostics: [] };
  }
  const diagnostics: Diagnostic[] = [];
  const named = new Map<ConceptId, Set<string>>();
  const namespaces = new Map<ConceptId, string>();
  const owners = new Map<string, ConceptId>();
  const importName = (conceptId: ConceptId, name: string): void => {
    const owner = owners.get(name);
    if (owner !== undefined && owner !== conceptId) {
      diagnostics.push(
        error(sync.file, `sync needs '${name}' from both ${owner} and ${conceptId}; rename one of them`, { line: 1 }),
      );
      return;
    }
    owners.set(name, conceptId);
    const names = named.get(conceptId) ?? new Set<string>();
    names.add(name);
    named.set(conceptId, names);
  };

  const when = parseActionRef(fm.when);
  const whenInfo = exportsByConcept.get(when.conceptId);
  if (whenInfo === undefined) {
    return { source: null, diagnostics };
  }
  let event: string[];
  if (whenInfo.functions.includes(when.member)) {
    importName(when.conceptId, when.member);
    event = [
      `  readonly args: Parameters<typeof ${when.member}>;`,
      `  readonly result: Awaited<ReturnType<typeof ${when.member}>>;`,
    ];
  } else {
    const cls = primaryClassName(when.conceptId);
    importName(when.conceptId, cls);
    event = [
      `  readonly target: ${cls};`,
      `  readonly args: Parameters<${cls}['${when.member}']>;`,
      `  readonly result: Awaited<ReturnType<${cls}['${when.member}']>>;`,
    ];
  }

  const actionsByTarget = new Map<ConceptId, string[]>();
  for (const ref of fm.then) {
    const { conceptId, member } = parseActionRef(ref);
    actionsByTarget.set(conceptId, [...(actionsByTarget.get(conceptId) ?? []), member]);
  }
  const targets: string[] = [];
  for (const [conceptId, members] of actionsByTarget) {
    const info = exportsByConcept.get(conceptId);
    if (info === undefined) {
      return { source: null, diagnostics };
    }
    const key = targetKey(conceptId);
    if (members.every((member) => !info.functions.includes(member))) {
      const cls = primaryClassName(conceptId);
      importName(conceptId, cls);
      targets.push(`  readonly ${key}: ${cls};`);
    } else {
      const alias = `${key}Module`;
      namespaces.set(conceptId, alias);
      targets.push(`  readonly ${key}: typeof ${alias};`);
    }
  }

  const imports = [...new Set([...named.keys(), ...namespaces.keys()])].sort().flatMap((conceptId) => {
    const lines: string[] = [];
    const names = named.get(conceptId);
    if (names !== undefined) {
      lines.push(`import { ${[...names].sort().join(', ')} } from '${relativeImport(sync.id, conceptId)}';`);
    }
    const alias = namespaces.get(conceptId);
    if (alias !== undefined) {
      lines.push(`import * as ${alias} from '${relativeImport(sync.id, conceptId)}';`);
    }
    return lines;
  });

  const source = [
    `// @generated by ccc from sync ${sync.id}. Do not edit.`,
    ...imports,
    '',
    'export interface SyncEvent {',
    ...event,
    '}',
    'export interface SyncTargets {',
    ...targets,
    '}',
    'export function handle(event: SyncEvent, targets: SyncTargets): Promise<void>;',
    '',
  ].join('\n');
  return { source, diagnostics };
}
